server:
  port: 8106

spring:
  application:
    name: stats-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}

logging:
  file:
    name: logs/stellar-ink-stats.log
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: info
    com.stellarink: debug
